#-------------------
# Site metadata
#-------------------

baseurl = "https://jossemargt.com"
url = "https://jossemargt.com"
title = "JossemarGT"
theme = "diary"
DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir= true

[languages]
  [languages.es]
    contentDir = "content/es"
  [languages.en]
    contentDir = "content/en"

[author]
  name = "Jossemar Cordero"
  github = "jossemargt"
  linkedin = "in/jossemargt"

[params]
  subtitle = "# tar -xzf /var/log/thoughts.log.0.gz"
  commit = "https://github.com/jossemarGT/jossemargt.com/tree/"
  mainSections = ["post", "posts"]
  dateFormat = "2006-01-02"
  enableAutoDarkMode = true
  comments = false
  hideAuthor = true

#---------------
# Theme configs
#---------------
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true

#---------------
# Social media
#---------------
enableOpenGraph = true
enableTwitterCards = true
title = "JossemarGT"
description = "# tail -f /var/log/thoughts.log"

#------------------
# Fixed menu items
#------------------

[[languages.es.menu.main]]
name = "Inicio"
url = "/es/"
weight = 10

[[languages.es.menu.main]]
name = "Acerca de Mi"
url = "/es/page/about/"

[[languages.es.menu.main]]
name = "English"
url = "/en/"

[[languages.en.menu.main]]
name = "Home"
url = "/en/"
weight = 10

[[languages.en.menu.main]]
name = "About me"
url = "/en/page/about/"

[[languages.en.menu.main]]
name = "Español"
url = "/es/"

#-------------------------------
# og:image generation font tweak
#-------------------------------
[security.http]
mediaTypes = ['^font/woff2$']
