#-------------------
# Site metadata
#-------------------

baseurl = "http://jossemargt.com"
url = "http://jossemargt.com"
DefaultContentLanguage = "es"
title = "JossemarGT"
theme = "beautifulhugo"

[languages]
  [languages.es]
    contentDir = "content/es"
  [languages.en]
    contentDir = "content/en"

[Author]
  name = "Jossemar Cordero"
  github = "jossemargt"
  linkedin = "in/jossemargt"

[Params]
  subtitle = "# tail -f /var/log/thoughts.log"
  commit = "https://github.com/jossemarGT/jossemargt.com/tree/"
  mainSections = ["post","posts"]
  dateFormat = "2006-01-2"
  comments = false
  hideAuthor = true

#---------------
# Theme configs
#---------------
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true

#---------------
# Fixed pages
#---------------

[[languages.es.menu.main]]
name = "Acerca de Mi"
url = "page/acerca-de-mi/"

[[languages.en.menu.main]]
name = "About"
url = "page/about/"
