baseurl = "http://jossemargt.com/"
languageCode = "es-es"
title = "JossemarGT"
theme = "beautifulhugo"

# Theme configs
pygmentsUseClasses = true
url = "http://jossemargt.com/"
#disqusShortname = "ENV_DISQUS"
#googleAnalytics = "ENV_ANALYTICS"

[Params]
  subtitle = "# tail -f /var/log/thoughts.log"

[Author]
  name = "Jossemar Cordero"
  github = "jossemargt"
  twitter = "jossemargt"
  linkedin = "in/jossemargt"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Acerca de Mi"
    url = "/page/about/"
    weight = 2
